### ISSUE TITLE
ERC20 bytearray 

### ISSUE THREAD

**Issue by SheStealsMyPenta** [OpenZeppelin/cairo-contracts#1035]
**📝 Details**
 for now ERC20 name attr is byte_array, but i can only use felt 252 to the outside interface, how to convert felt 252 to byte_array? Furthermore, if  use the bytearray as a input , how to filled into constructor?

**🔢 Code to reproduce bug**

**Comment by ericnordelo** [comment]
ByteArray is a struct implementing Serde ([defined here](https://github.com/starkware-libs/cairo/blob/d63c45b32cb367d8e9bd830ab598d02a0c24bee8/corelib/src/byte_array.cairo#L24)). Like any other serializable type, you can convert it into an `Array<felt252>`, which is the type required as calldata. Dispatchers do this process of serializing and deserializing the call for you. 

I'm closing the issue since it is more fit for the discussions category.
