### ISSUE TITLE
Transaction malleability in the account contract

### ISSUE THREAD

**Issue by bbrandtom** [OpenZeppelin/cairo-contracts#105]
Currently, the account contract does not verify that the `nonce` in the transaction call data is equal to the `current_nonce` in the contract, but only that the user signed on the `current_nonce`. This allows a malicious sequencer to replace `nonce` with an arbitrary felt. This results in a malleable vulnerability since the sequencer can change the transaction hash, while still being able to execute the transaction.

**📝 Details**

I suggest adding an assert in the `execute()` function, that verifies that the `nonce` in the call data is equal to the `current_nonce` in the contract storage.

**Comment by martriay** [comment]
Thanks for reporting this, I can confirm is indeed correct. After a brief analysis, this seems to be a minor issue since malleability on shared state blockchains (e.g. StarkNet, Ethereum) is much less likely to attacks than in Bitcoin for example, the reason being the nonces which help users to keep track of sent and executed transactions. There's little harm an attacker could cause under very specific conditions.

In any case this **is** an attack vector and we will fix it asap.
