### ISSUE TITLE
Can't compile contract after fresh repo clone

### ISSUE THREAD

**Issue by l-henri** [OpenZeppelin/cairo-contracts#106]
I am trying to clone the repo and compile the contracts, and I follow the instructions.
An error pops up while I compile
```
contracts/Pausable_base.cairo:13:9: Unexpected implicit argument 'pedersen_ptr' in an external function.
        pedersen_ptr: HashBuiltin*,
        ^**********^
contracts/token/ERC20_base.cairo:65:9: Unexpected implicit argument 'pedersen_ptr' in an external function.
        pedersen_ptr : HashBuiltin*,
        ^**********^
contracts/token/ERC721.cairo:122:20: Unknown identifier 'total_supply'.
    let (supply) = total_supply.read()
                   ^***************^
```
The json artifacts are empty, and these files are not compiled.

**📝 Details**
Pretty much that's it
**🔢 Code to reproduce bug**
```
git clone https://github.com/OpenZeppelin/cairo-contracts
cd cairo-contracts
python3 -m venv env
source env/bin/activate
pip install cairo-nile
nile install
nile compile
```

**Comment by martriay** [comment]
@l-henri yes, this is a known problem [of the extensibility pattern](https://community.starknet.io/t/contract-extensibility-pattern/210). This is because base contracts can't declare builtins, only frontend contracts. Without them, base contracts won't compile.

I have raised this with the starkware team already, hopefully they will fix it. In the meantime, avoid compiling base contracts.

**Comment by liorzilp** [comment]
@martriay, the problem is that ERC20.cairo doesn't compile as well because of this dependency. Any workaround?
