### ISSUE TITLE
Specifying snforge_std as dependency can cause version collision

### ISSUE THREAD

**Issue by amanusk** [OpenZeppelin/cairo-contracts#1082]
Tried importing the latest version of cairo-contracts, but using it in a project which uses a different version of snforge_std causes a dependency collision

**📝 Details**

Importing OZ contracts which use snforge_std 0.26.0, in a project which uses snforge_std 0.27.0 results in a dependency collision

```    Updating git repository https://github.com/foundry-rs/starknet-foundry
error: found dependencies on the same package `snforge_std` coming from incompatible sources:
source 1: git+https://github.com/foundry-rs/starknet-foundry.git?tag=v0.27.0#2d99b7c00678ef0363881ee0273550c44a9263de
source 2: git+https://github.com/foundry-rs/starknet-foundry.git?tag=v0.26.0#50eb589db65e113efe4f09241feb59b574228c7e
[ERROR] error: could not gather project metadata from Scarb due to previous error: `scarb metadata` exited with error

stdout:
    Updating git repository https://github.com/foundry-rs/starknet-foundry
error: found dependencies on the same package `snforge_std` coming from incompatible sources:
source 1: git+https://github.com/foundry-rs/starknet-foundry.git?tag=v0.27.0#2d99b7c00678ef0363881ee0273550c44a9263de
source 2: git+https://github.com/foundry-rs/starknet-foundry.git?tag=v0.26.0#50eb589db65e113efe4f09241feb59b574228c7e

stderr:
```

The project specifies snforge_std as dev-dependency, but the issue still exists.
The cause seems to be since `utils` uses snforge_std as dependency and not dev-dependency https://github.com/OpenZeppelin/cairo-contracts/blob/eabfa029b7b681d9e83bf171f723081b07891016/packages/utils/Scarb.toml#L21, and cairo-contracts depend on `utils`
https://github.com/OpenZeppelin/cairo-contracts/blob/eabfa029b7b681d9e83bf171f723081b07891016/Scarb.toml#L11

**🔢 Code to reproduce bug**

Running `snforge test` on this repo and branch will produce the bug
https://github.com/amanusk/starknet-foundry-template/tree/bug/sn-foundry-collision

Tagging @piotmag769 who helped identify the bug

**Comment by ericnordelo** [comment]
Thanks for such a detailed report @amanusk. Will work on fixing this asap.

**Comment by ericnordelo** [comment]
I've been thinking of potential solutions for this issue, and there's seems not to be an easy one at least until [this PR](https://github.com/foundry-rs/starknet-foundry/pull/2056) is merged for scarb, since we are reusing test utilities and common modules among packages, and there seems not to be a way to share dev-dependencies among them.

A temporal solution could be replicating the common modules and the test utilities among all the modules, just to not share the test utils, but that's far from appropriate and not worth it IMO.

Let's update to the latest foundry release before releasing 0.15.0, and wait for the scarb update to fix this issue.

**Comment by ericnordelo** [comment]
cc @andrew-fleming
