### ISSUE TITLE
Transfer ownership in the RBAC component

### ISSUE THREAD

**Issue by fvelazquez-X** [OpenZeppelin/cairo-contracts#1161]
**📝 Details**
I am currently reviewing the RBAC (Role-Based Access Control) component and have observed that it offers highly granular control for assigning roles. However, it appears to lack an efficient mechanism for transferring administrative or ownership rights, aside from the use of the `_set_role_admin` function, which does not seem ideal for this purpose. 

Is there an alternative function available to facilitate the transfer of ownership? If not, would it be advisable to introduce a `transfer_ownership` function within this context? This suggestion stems from the fact that there is already an admin role (a default admin, in principle) in RBAC, and such a function might enhance the component.

Alternatively, would you recommend integrating somehow the RBAC with the Ownable component to leverage the ownership transfer functionality provided there?

Thank you in advance for your guidance!

**Comment by ericnordelo** [comment]
Hey @fvelazquez-X, having certain control over the default admin is certainly helpful, and we have an extension in our Solidity library that addresses what you are mentioning: [AccessControlDefaultAdminRules](https://docs.openzeppelin.com/contracts/5.x/api/access#AccessControlDefaultAdminRules). We have an open issue (#1164)  tracking the feature. We are planning on taking it next milestone, which should start in around three weeks. As a matter of terminology, the default admin is not exactly an owner, and also for the sake of simplicity, I wouldn't try to leverage the Ownable component implementation for this, but an AccessControl-specific extension.

Closing the issue since we already have another one tracking the feature.
