### ISSUE TITLE
Transfer ownership for Cairo 0

### ISSUE THREAD

**Issue by fvelazquez-X** [OpenZeppelin/cairo-contracts#1181]
There are still few projects built on Cairo 0 and I would like to know if there is a library for 2 step transfer ownership

I would like to know if this is feasible or would it make sense since Cairo 0 is already quite old but I understand it is still mantained and used. 

Thank you!

**Comment by ericnordelo** [comment]
Hey @fvelazquez-X, the library doesn't support cairo 0 contracts anymore. Even whenthey are still supported, they are deprecated and will be removed at some point with regenesis. My understanding is that new cairo 0 contract classes [can't be declared anymore](https://community.starknet.io/t/blocking-cairozero-class-declarations/113807), so it doesn't make sense for anyone to continue developing new modules for that version.

Closing since there's no further actions to take, but feel free to [open up a discussion](https://github.com/OpenZeppelin/cairo-contracts/discussions) if you have more questions.
