### ISSUE TITLE
Add eth signature support to Account

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#161]
https://twitter.com/LiorGoldberg2/status/1471091591620304904?s=20

**Comment by JulissaDantes** [comment]
Documentation: The way they implemented the verification was receiving the x and y components of the signature, and with them form a `EcPoint`, but the way the Cairo contract Account stores the key is using a `felt` because the `private_to_stark_key` function returns an int, even if the actual return is type `EcPoint`.

**Comment by pscott** [comment]
Looks like 0.8.2 shipped it! :)

https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/cairo_secp/signature.cairo#L202-L239

**Comment by JulissaDantes** [comment]
When trying to use the eth signature verification methods inside the new 0.8.2 version, I get an error and after I finish writing the tests this development will be on hold by that. See: [#64](https://github.com/starkware-libs/cairo-lang/issues/64)

**Comment by JulissaDantes** [comment]
Documentation: after a slack conversation the design of this development will be 2 pairs of validation and execution functions, and an `unsafe_execute` function.
