### ISSUE TITLE
Can't use IAccount.cairo interface

### ISSUE THREAD

**Issue by l-henri** [OpenZeppelin/cairo-contracts#291]
Hello,

I want to write a contract that calls an account contract to perform some action. In order to do that I import IAccount.cairo in my file, but I can't

**📝 Details**
IAccount.cairo imports a function from [Account.cairo ](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/IAccount.cairo#L6). 
The constructor of Account is imported in IAccount, and then imported in my contract. This makes it impossible to write my constructor, and it also gives an improper constructor to my contract.

**🔢 Code to reproduce bug**

Import IAccount in a contract
Define a constructor

**Comment by andrew-fleming** [comment]
Hey @l-henri, thanks for posting this issue! IAccount is importing from the Account contract instead of the library; thus, the constructor and all other exposed methods are imported with it (which they shouldn't). Changing IAccount's import to this: `from openzeppelin.account.library import AccountCallArray` should fix this issue. I'll submit a PR with the update. Thanks, again :)

**Comment by andrew-fleming** [comment]
> How can we prevent this kind of issues. Should we test interfaces?

Given how exposed methods are auto-exported, I think we should.
