### ISSUE TITLE
Distinguish API docs between preset and library

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#369]
Today our docs mix up APIs for presets and libraries, and some section focus on either lib or preset inconsistently. Also, initializers/constructors are not properly documented in may sections.

**Comment by andrew-fleming** [comment]
Since the token docs list the exposed API according to the EIP spec, maybe we should also include a `library API` a la [https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20) (but with the snake_cased methods). I think that's where token `initializer`s belong as well.

**Comment by ericglau** [comment]
There is also some inconsistency between what is documented: library or interface.

For example:
- [ownable](https://docs.openzeppelin.com/contracts-cairo/0.3.1/access#ownable_library_api), [access control](https://docs.openzeppelin.com/contracts-cairo/0.3.1/access#accesscontrol_library_api), and [upgrades](https://docs.openzeppelin.com/contracts-cairo/0.3.1/proxies#upgrades_library_api) have their library API documented (with snake case).
- [ERC20](https://docs.openzeppelin.com/contracts-cairo/0.3.1/erc20#api_specification) and [ERC721](https://docs.openzeppelin.com/contracts-cairo/0.3.1/erc721#api_specification) have their interface API documented (with camel case) in their API Specification section.  But their interface is also listed at the top of the document [here](https://docs.openzeppelin.com/contracts-cairo/0.3.1/erc20#interface) and [here](https://docs.openzeppelin.com/contracts-cairo/0.3.1/erc721#ierc721).

Perhaps ERC20 and ERC721's "API Specification" sections should be changed to library API instead of interface API.

**Comment by martriay** [comment]
> There is also some inconsistency between what is documented: library or interface or both.

Indeed, I though we had an issue to track this but I couldn't find it. We need docs for libraries and presets separated.

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
