### ISSUE TITLE
Unsafe use case of `ownable.cairo`

### ISSUE THREAD

**Issue by nikitastupin** [OpenZeppelin/cairo-contracts#374]
**🧐 Motivation**

The [assert_only_owner](https://github.com/OpenZeppelin/cairo-contracts/blob/cf85bbd8181f86b55fae63816589846ebf7bd3d0/src/openzeppelin/access/ownable.cairo#L44-L55) protector doesn't check if the owner is 0 thus when one calls the [renounce_ownership](https://github.com/OpenZeppelin/cairo-contracts/blob/cf85bbd8181f86b55fae63816589846ebf7bd3d0/src/openzeppelin/access/ownable.cairo#L83-L91) function and therefore sets the owner to 0, they are allowing anyone to call [assert_only_owner](https://github.com/OpenZeppelin/cairo-contracts/blob/cf85bbd8181f86b55fae63816589846ebf7bd3d0/src/openzeppelin/access/ownable.cairo#L44-L55)-protected functions (because in StarkNet by default transactions come from 0) instead of denying anyone to call these functions.

**📝 Details**

Since Cairo 0.9.0 we have the mandatory fees and it's not possible to call any contract from 0 address. However, account contracts are still called from 0 address. To mitigate the unsafe use case of `ownable.cairo` in conjunction with an account contract I suggest to either add 0 address check or add comment on that.

**Comment by 0xSidius** [comment]
temp comment is fine

**Comment by martriay** [comment]
> However, account contracts are still called from 0 address.

Our current design is based on a [single entrypoint](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/Account.md#account-entrypoint), meaning that the only function you'll call as the zero address is `__execute__`, which don't need `ownable` to manage access (there's `__validate__` for that). The sole scenario in which this could be an issue is when someone implements a very custom account, departing from our lib design, but using our library's `ownable`.

My personal opinion here is that we shouldn't accommodate the library for such custom cases, since they bear its own risk and therefore should require full understanding of the code being written. I think in this case there's no big drawback of adding the check, but I wanted to state this so it serves as future reference for criteria.
