### ISSUE TITLE
EIP-712 / SNIP-12

### ISSUE THREAD

**Issue by EdgarBarrantes** [OpenZeppelin/cairo-contracts#409]
**🧐 Motivation**

[EIP-712](https://eips.ethereum.org/EIPS/eip-712) is implemented in a [draft](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/draft-EIP712.sol) in the solidity contracts. It seems like a good idea to implement in cairo as well considering that Argent-X [seems to be using it it](https://github.com/argentlabs/argent-x/discussions/14). 

**📝 Details**

I'm not entirely sure about Cairo's capabilities for this. The standard library does [support keccak](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/keccak.cairo). Everything would be a felt as well.
Any guidance on how one would approach this is highly appreciated.

**Comment by remiroyc** [comment]
The [repository](https://github.com/ruleslabs/starknet-messages/tree/main) developed by @0xChqrles offers an ideal foundation for initiating this PR. It enables computing typed data hash, checking their signature, and consuming them.

@martriay What changes do you think are needed to integrate this feature into OZ? I believe it's an important feature because all wallets rely on an EIP-712 signature method implemented by starknetjs, and it's important to have the capability to recompute this hash on-chain.

**Comment by 0xChqrles** [comment]
Thank you for mentioning my repo ! It only supports [SNIP-12](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md) revision 0 but I would be glad to help supporting revision 1 too !
