### ISSUE TITLE
DOC: Fix Wizard position in docs to be consistent with the Solidity library doc site

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#462]

**Comment by martriay** [comment]
It was a conscious decision of mine to move it at the very bottom, since I thought it added noise in an already hard to approach doc.

Basically, I didn't want people to go from overview directly into wizard, without understanding the extensibility pattern first (which unlike Solidity, is not as obvious as "just inherit").

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1703831/189489775-d83d4a0e-45ff-4b55-b194-6e0b71afa539.png">

^ note how extensibility is suggested as next step at the very bottom of the Overview page.

That being said I recognize the inconsistency, so I'll just explain my rationale to better discuss what's better. Interested in @frangio's thoughts.

**Comment by ericnordelo** [comment]
Makes sense @martriay. Just to mention that there is another change in the PR that is not the position in the nav menu, but embedding the Wizard instead of redirecting outside the docs site (as is done also in Soldity docs site). Even if we let the Wizard below, should we keep this?

**Comment by ericnordelo** [comment]
Maybe we could let the Wizard in the top (below Overview), but with the embedded version, letting an important note section on top of the wizard frame strongly suggesting to check the Extensibilty Pattern page first? Basically the user would see this note before the wizard code even when the wizard nav position is on top.

As a developer, I usually open the openzeppelin contracts doc site just to go to the wizard an copy the baseline code for a project. Having the wizard on top is a (maybe slight but certainly) better UX. I understand now that going directly to the https://wizard.openzeppelin.com/ page would be faster, but I didn't know the wizard was published on a separate site by then.

**Comment by martriay** [comment]
I understand. I think it's ok as long as we mention and link to extensibility in the wizard doc page :)

**Comment by frangio** [comment]
I would favor putting Wizard near the top, it can be a good way for people to get a feel. We can include a mention of the extensibility pattern if we're using the embed.
