### ISSUE TITLE
Migrate SRC5 to component

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#754]

**Comment by martriay** [comment]
no strong opinions regarding splitting #751 into multiple issues vs simply targeting all PRs to the general one. thoughts?

**Comment by ericnordelo** [comment]
I think we should at least split it, and base one PR in a previous one (scale step by step). If we do just one, is going to be a very big PR, and very hard to review.

**Comment by ericnordelo** [comment]
I already created the PRs btw, I see they are not linked, let me do that manually.

**Comment by martriay** [comment]
> If we do just one, is going to be a very big PR, and very hard to review.

I was talking about splitting the issues, not the PR. That's why I said "targeting all PRs to the general one", being the general issue.

I would definitely NOT base each PR in the previous one (step by step). That creates a dependency hell where a PR might be ready but it's blocked by several previous ones. I should have passed that feedback from the docs one.

What we should do, as we did with the Cairo 1 migration, is to have at moste ONE base PR (like Account was for docs) and have all the other ones depend on that single one, and the rest can be worked out in parallel.
