### ISSUE TITLE
What is the reason? Can you help me solve it?

### ISSUE THREAD

**Issue by my-Gem** [OpenZeppelin/cairo-contracts#816]
![2023-11-08_175427](https://github.com/OpenZeppelin/cairo-contracts/assets/26290087/368bc966-fae1-49d4-b227-202ea77226f6)

**Comment by martriay** [comment]
hey there @my-Gem. Please make sure to explain a bit what you've done, how your setup looks, and all necessary details to reproduce the issue, otherwise we can't properly help.

It looks like git is not being able to fetch the repository, maybe you're lacking read access to github, or write access in your system. Either way this doesn't seem to be an openzeppelin contracts issue, so I'll close. Feel free to open a new, more detailed issue if you think this is a mistake. Good luck!
