### ISSUE TITLE
ERC721 token

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#9]

**Comment by martriay** [comment]
1. I believe we need _at least_ to copy + freeze metadata from L1, querying information should be made easy. This means not having to make inter-layer calls to get metadata from L1 when looking at an L2 token. Dynamic `tokenUri`s are definitely and additional challenge.
2. what do you mean by distinguishing?

I also wonder how NFTs bridges should/will look like.

**Comment by fracek** [comment]
> 1. I believe we need _at least_ to copy + freeze metadata from L1, querying information should be made easy. This means not having to make inter-layer calls to get metadata from L1 when looking at an L2 token. Dynamic `tokenUri`s are definitely and additional challenge.

Agree. On the other hand users could query information that is outdated or wrong which is pretty dangerous. Basically I'm wondering if we can make it convenient and foolproof. 

> 2. what do you mean by distinguishing?

If I'm writing a dapp frontend I want to know if the ERC-721 I'm looking at is an L2 one or bridged. If it's bridged I want to know what's the original L1 token so that, for example, I can use the L1 `tokenUri` method to correctly support dynamic NFTs (or I can fetch analytics data about the L1 collection). I'm thinking like creating a new interface for bridged ERC-721:

```solidity
interface BridgedERC721 {
    function l1Address() view returns address;
    function l1ChainId() view returns uint256;
}
```

> I also wonder how NFTs bridges should/will look like.

I started thinking about this too and I would love to hear more from others. At the moment there are not many NFT bridges available. One advantage of StarkNet is that it should be possible to go back from L2 to L1 in less than a day and not a week like other Layer 2.

**Comment by perama-v** [comment]
I wonder, for the tokens that originate in L2, what the pattern is in the event of a roll-up fallback event. You inherit the L1 security and can recover your token on L1 (at some cost). This would involve minting, and does this imply that an L2 token points to a contract factory on L1?

**Comment by shrugs** [comment]
if L1 token doesn't support metadata, neither should L2, since there's nothing to display, right?

**Comment by fracek** [comment]
Sorry I didn't express myself clearly. How would a dapp or smart contract know a token is a bridged token if they cannot inspect the tokenuri? Should a dapp even care if a token is bridged if there is no token uri?

**Comment by frangio** [comment]
There is a project to register a `caip:` URI scheme (https://github.com/ChainAgnostic/CAIPs/issues/67). I wonder if it would be ok to  use that directly? That is, a `caip` URI referencing the original asset. It is not specifically referencing the tokenURI, but I don't know if that's an issue.

**Comment by shrugs** [comment]
yeah that seems ideal tbh
